# Use an official Ubuntu as a parent image
FROM condaforge/miniforge3

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

LABEL org.opencontainers.image.description="""\
This image is used to run the EQASIM pipeline. It contains the necessary dependencies to build the project : \
\
- Java 17 \
- Maven \
- Python 3 & Conda \
- Osmosis 0.48.3 \
- Git \
\
It also creates a conda environment named 'eqasim' with the dependencies specified in the environment.yml file. \
The environment.yml file can be specified using the 'env_path' build argument. If not specified, the default environment.yml file from the repository will be used.\
"""

ARG env_path

# Install dependencies
RUN apt-get update && apt-get install -y \
    openjdk-17-jdk \
    maven \
    python3 \
    python3-pip \
    wget \
    unzip \
    git \
    && apt-get clean

# Set path to conda
ENV PATH=/opt/conda/bin:$PATH

# Verify installations
RUN java -version && \
    mvn -version && \
    python3 --version && \
    conda --version 

COPY ./environment.yml /tmp/environment_eqasim.yml

# Copy the environment.yml file into the container if env_path is set (else will create an empty directory)
COPY ${env_path} /tmp/environment_custom.yml

# Check if env_path is set, if not use from the repo
RUN if [ -z "$env_path" ]; then \
        mv /tmp/environment_eqasim.yml /tmp/environment.yml; \
    else \
        mv /tmp/environment_custom.yml /tmp/environment.yml; \
    fi

# Create the conda environment
RUN conda env create -f /tmp/environment.yml -n eqasim

# Activate the environment
RUN echo "source activate eqasim" > ~/.bashrc